@SoftWizard_HostAddress = https://localhost:7229

GET {{SoftWizard_HostAddress}}/api/users
Accept: application/json

###

DELETE {{SoftWizard_HostAddress}}/api/users/delete/3
Accept: application/json

###


GET {{SoftWizard_HostAddress}}/api/okpd
Accept: application/json

###
GET {{SoftWizard_HostAddress}}/api/okpd/11
Accept: application/json

###
